# Generated by Django 6.0.3 on 2026-03-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='AUID',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(),
        ),
    ]
